# Generated by Django 2.2 on 2019-04-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('prices', models.CharField(choices=[('К', 'Красный'), ('Ж', 'Желтый'), ('Б', 'Белый')], max_length=10)),
            ],
        ),
    ]
