# Generated by Django 2.2 on 2019-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plitka', '0005_auto_20190429_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
