# Generated by Django 2.2 on 2019-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plitka', '0008_auto_20190429_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='prices',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to='category'),
        ),
    ]
