# Generated by Django 2.2 on 2019-05-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plitka', '0010_auto_20190514_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
