# Generated by Django 2.2 on 2019-05-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plitka', '0011_auto_20190514_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(default=None, upload_to='item')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plitka.Category')),
            ],
        ),
    ]
