# Generated by Django 2.2 on 2019-05-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plitka', '0014_auto_20190514_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default=None, max_length=150, verbose_name='Ссылка'),
        ),
    ]
